add_newline = true

format = """
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$memory_usage\
$aws\
$env_var\
$custom\
$jobs\
$battery\
$time\
$status\
$line_break\
$character"""
