num_src_files=$(ls "$G_ASYNC_WORKER_OUTPUT_DIR/$G_ASYNC_WORKER_OUTPUT_SRC_REL_DIR" | wc -l);
if [[ "$num_src_files" -gt 0 ]]; then
    cat $G_ASYNC_WORKER_OUTPUT_DIR/$G_ASYNC_WORKER_OUTPUT_SRC_REL_DIR/* > "$G_ASYNC_WORKER_OUTPUT_DIR/$G_ASYNC_WORKER_OUTPUT_SRC_MERGED_FILENAME"
fi;